@echo off
setlocal enabledelayedexpansion

echo ========================================
echo   Class Scanner CLI Tool Installer
echo ========================================
echo.

REM Check for Java
java -version >nul 2>&1
if %ERRORLEVEL% neq 0 (
    echo Error: Java is not installed or not in PATH.
    echo Please install Java 11 or later and add it to your PATH.
    exit /b 1
)

echo Step 1: Building the project...
call gradlew clean shadowJar

if %ERRORLEVEL% neq 0 (
    echo Build failed!
    exit /b 1
)

echo Step 2: Installing CLI tool...

REM Check if JAR exists
if not exist "build\libs\class-scanner-1.0-SNAPSHOT-all.jar" (
    echo Error: JAR file not found after build.
    exit /b 1
)

REM Create C:\bin directory if it doesn't exist
if not exist "C:\bin" (
    echo Creating C:\bin directory...
    mkdir "C:\bin"
    if !ERRORLEVEL! neq 0 (
        echo Error: Failed to create C:\bin directory. Run as administrator.
        exit /b 1
    )
)

REM Copy JAR to C:\bin
echo Copying JAR file to C:\bin...
copy "build\libs\class-scanner-1.0-SNAPSHOT-all.jar" "C:\bin\class-scanner.jar" >nul
if %ERRORLEVEL% neq 0 (
    echo Error: Failed to copy JAR file. Run as administrator.
    exit /b 1
)

REM Create batch wrapper
echo Creating class-scanner.bat wrapper...
(
echo @echo off
echo REM Class Scanner CLI Tool
echo REM Generated by install script
echo java -jar "C:\bin\class-scanner.jar" %%*
) > "C:\bin\class-scanner.bat"

if %ERRORLEVEL% neq 0 (
    echo Error: Failed to create batch wrapper. Run as administrator.
    exit /b 1
)

echo Step 3: Configuring PATH...

REM Check if C:\bin is in PATH
echo %PATH% | findstr /i "C:\bin" >nul
if %ERRORLEVEL% neq 0 (
    echo Adding C:\bin to system PATH...

    REM Try to add to system PATH (requires admin privileges)
    setx PATH "%PATH%;C:\bin" /M >nul 2>&1
    if !ERRORLEVEL! equ 0 (
        echo C:\bin added to system PATH successfully.
        echo Please restart your command prompt to use the new PATH.
    ) else (
        echo Could not automatically add C:\bin to system PATH.
        echo Please add it manually:
        echo.
        echo 1. Open System Properties ^(Win + R, type 'sysdm.cpl'^)
        echo 2. Click 'Environment Variables'
        echo 3. Edit the 'Path' variable in 'System variables'
        echo 4. Add 'C:\bin' to the list
        echo 5. Restart your command prompt
    )
) else (
    echo C:\bin is already in PATH.
)

echo.
echo ========================================
echo   Installation completed successfully!
echo ========================================
echo.
echo Files installed:
echo   C:\bin\class-scanner.jar
echo   C:\bin\class-scanner.bat
echo.
echo Usage:
echo   class-scanner --help
echo   class-scanner maven ^<maven-root^> ^<class-name^>
echo   class-scanner class ^<class-file^> [additional-classpath...]
echo.
echo Examples:
echo   class-scanner maven C:\Projects\my-app com.example.MyClass
echo   class-scanner class MyClass.class lib1.jar lib2.jar
echo.
echo Test the installation:
echo   class-scanner --help

pause
